### ISSUE TITLE
Implement lookup_value_regex for nested resources

### ISSUE THREAD

**Issue by H0neyBadger** [alanjds/drf-nested-routers#39]
With DRF 3, ViewSet’s **lookup_value_regex** property isn’t properly passed to the **SimpleRouter** overridden class.

I think you can remove the SimpleRouter from **/rest_framework_nested/routers.py** and use the default DRF **SimpleRouter.get_lookup_regex**

tested on :
 - Django 1.7
 - DRF 3
 - Python 3

**Comment by clintonb** [comment]
I have confirmed that simply using the DRF's default `SimpleRouter` resolves this issue.

**Comment by qubird** [comment]
This works to me, using DefaultRouter and NestedSimpleRouter. 

Sure this will be save time to many people:

I'm using UUIDs, so my regex was: `[0-9a-f]{32}`.

This was making the router falling over url formatting, because `{32}` is a meta-expression for python string formatting. I replaced `{32}` with `{{32}}` and it now works.

**Comment by stevejalim** [comment]
I think that `{{32}}` find deserves a prize

**Comment by alanjds** [comment]
Hi. Can you issue a PR for DRF 3 compatibility?, or at least explain an example on the README?

**Comment by mrhwick** [comment]
This should all be fixed by #60 and #58

**Comment by alanjds** [comment]
@mrhwick #60 and #58 was both merged. Can I close this one?

**Comment by mrhwick** [comment]
@H0neyBadger was the original poster of the issue, but I would be surprised if any of the issues mentioned here are still outstanding with the latest fixes.

**Comment by alanjds** [comment]
Closing. @H0neyBadger: Feel free to reopen if there is still an issue.
