### ISSUE TITLE
Creation of new nested objects

### ISSUE THREAD

**Issue by stevelacey** [alanjds/drf-nested-routers#54]
How do you recommend handling the creation of new nested objects at the nested list endpoint and getting them to be bound to the parent?

At the moment I get an integrity error as it is trying to leave the foreign key null, and am having varying success slotting the parent in at different points in the serializer/viewset create/save flow. Closest I've gotten does it after validation has occurred by modifying the data by overriding the serializer create, which means uniqueness constraints I have in place fail to get caught, and thus a db exception is thrown if I pass something invalid rather than a friendly error.

Any thoughts?

**Comment by ryanhiebert** [comment]
I've been struggling with this for the past couple of days myself, and I think I've figured it out.

`GenericAPIView`, a superclass of your `ModelViewSet` subclasses, adds some extra stuff to the `context` of your serializer when it's instantiated. In particular, it adds `request`, `format`, and `view`.

https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/generics.py#L131

This means that you can override the `save()` method on your serializer to add the extra field based on that context. For example:

```python
from .models import Basket, Fruit

class NestedFruitSerializer(Serializer):
    class Meta:
        model = Fruit
        fields = ['basket', 'name']

    def save(self, *args, **kwargs):
        basket_pk = self.context['view'].kwargs['basket_pk']
        kwargs['basket'] = Basket.objects.get(pk=basket_pk)
        return super(NestedFruitSerializer, self).save(*args, **kwargs)
```

Or something like that. I hope that helps you get on the right path.

**Comment by stevelacey** [comment]
I forgot I created this issue, and now I can't remember how I solved it.

It looks like I did something similar, pass through the parent object (`attachable`) via the serializer context by overwriting `get_serializer_context` on the viewset – I made mine kind of generic since I have multiple viewsets for this model as `Attachment` can be generically bound to a few models in my system, in short I made up a `parent` attr that relates the nested viewset to its parent, then pluck the rest of the things I need out of that class's `Meta` e.g. the `mode_name` (so I can guess the nested kwarg equiv), `lookup_field`, etc:

```py
    parent = ExportViewSet

    def get_attachable(self):
        viewset = self.parent(request=self.request)
        kwarg = '{}_{}'.format(viewset.model._meta.model_name, viewset.lookup_field)
        return get_object_or_404(viewset.get_queryset(), **{viewset.lookup_field: self.kwargs.get(kwarg)})

    def get_serializer_context(self, *args, **kwargs):
        context = super(AttachmentViewSetMixin, self).get_serializer_context(*args, **kwargs)
        context['attachable'] = self.get_attachable()
        return context
```

Then in my serializer I overwrote `to_internal_value` like so.

```py

    def to_internal_value(self, data):
        data.update({
            'content_type': ContentType.objects.get_for_model(self.context['attachable']).pk,
            'object_id': self.context['attachable'].pk,
        })

        return super(AttachmentSerializer, self).to_internal_value(data)
```

Interesting that you chose `save` instead, not sure if my solution is any better – maybe it fits my generics/validation requirements better? I don't remember when validation happens in the DRF workflow. Either way this got the job done for me.

**Comment by ryanhiebert** [comment]
I'm not sure where validation happens either, and that may be something that bites me when I actually try to implement this. At this point, figuring out that it was possible was enough, because I know I'll need it soon. But I don't need it _right_ now, so I haven't tested it yet.

Thanks for your insight, it'll help me figure out the Right&trade; solution.

**Comment by ryanhiebert** [comment]
And security based on the parent viewset makes sense to me. I haven't figured out whether that's really how I want to do it or not, but it certainly makes sense. I'll have to consider it further. If it seems like a good idea, that's two people that need that, so maybe theres a package waiting to happen for that, or an improvement to this one.

**Comment by stevelacey** [comment]
I basically have custom `readable` and `writable` filter methods on the my model managers + querysets which I use for all of these – essentially means if the user cannot read/write (whichever role they have) the record, it doesn't end up in the queryset and thus they end up with 404's if they try and access them – which is what I want (for obscurity).

Attachments being things they attach to these already secured thing, inheriting it makes good sense.

**Comment by Diaoul** [comment]
Here is the mixin I created for child viewsets, it supports read/write operations

```python
class NestedViewSetMixin(object):
    parent = None
    parent_lookup_field = 'nested'

    def get_nested_filter_dict(self):
        filter_dict = {}
        if not self.parent:
            return filter_dict
        viewset = self.parent(request=self.request)
        if isinstance(viewset, NestedViewSetMixin):
            filter_dict.update(viewset.get_nested_filter_dict())
        filter_dict.update({self.parent_lookup_field:
                            self.kwargs.get('%s_%s' % (self.parent_lookup_field, viewset.lookup_field))})
        return filter_dict

    def get_queryset(self):
        return super(NestedViewSetMixin, self).get_queryset().filter(**self.get_nested_filter_dict())

    def perform_create(self, serializer):
        viewset = self.parent(request=self.request, kwargs={self.parent.lookup_field: self.get_nested_filter_dict().get(self.parent_lookup_field)})
        serializer.save(**{self.parent_lookup_field: viewset.get_object()})
```

Usage example:
```python
class ClientViewSet(viewsets.ModelViewSet):
    queryset = Client.objects.all()
    serializer_class = ClientSerializer

class ClientOrdersViewSet(NestedViewSetMixin, viewsets.ModelViewSet):
    parent = ClientViewSet
    parent_lookup_field = 'client'  # must be the same as in the router and your Order model
    queryset = Order.objects.all()
    serializer_class = ClientOrderSerializer  # I use read_only=True for the client property
```

I tested with GET/POST/PUT. Not yet with permissions and multi nested views but it should work.

**Comment by ryanhiebert** [comment]
@Diaoul: There's a lot to like about your approach, and it seems to make sense. I like that the parent seems to be explicit in the child ViewSet.

I like the approach, I think it's good work. I do see some deficiencies, but this may be a useful starting point.

There should be a parallel to `lookup_url_kwarg`, which is separate from the `parent_lookup_field`. This would allow me to use `client_id` as the url kwarg, instead of just `client`.

I also wonder if there is a reasonable place to check that the router URL config is properly matching the parent relationship as required by the view. At first glance, it seems to me that only the router would be able to check that, so it would have to be a special cased check when the ViewSet is determined to have used the `NestedViewSetMixin`.

-----------

And the one thing that I see that may kill this `get_nested_filter_dict` approach is that it doesn't take into account any of the custom queryset filtering that may have been implemented in the parent `ViewSet`. If that's a needed feature, that could really put a kink in things.

The most obvious solution would be to use the parent's `get_object` method (which uses `get_queryset`) to get the instance, and then follow a relationship on that object. That would require a separate query for each ViewSet, but would enforce all the parent's queryset constraints, as well as any permissions and filtering, on the parent as well, which I'm pretty certain that this would not be able to accomplish. Whether that's actually a good idea, or if it needs to be considered at the permission level is a good question.

**Comment by alanjds** [comment]
@Diaoul It looks very nice. As we got tests now (yay!), can you please bake one and lets work this solution into the repo?

@jsenecal: What you think? Any caveat?

**Comment by Diaoul** [comment]
@alanjds: as @ryanhiebert said, this is not a final product but rather a starting point. I focused on the API (nice and easy to use) and create/update capabilities. Not really the implementation which relies on nested router internals and is kinda convoluted. About permissions, it all comes down to which features we want here. I'm not into permissions in my project yet and will not likely need fine-grained permissions anyway, so if anybody has the use case and wants to jump in feel free to do it :)

**Comment by alanjds** [comment]
Yes. It is a starting point. But this whole thing grow from just that anyway ;)

We can create a branch (or some branches) and hack free before deciding on the final structure.

Anyway, I guess @ryanhiebert and me had a race-condition here, typed at the same time, as I had not his input when wrote mine.

**Comment by krische** [comment]
Is there a reason it can't just override the `create()`, `update()`, `partial_update()`, and `destroy()` methods of the `ViewSet` class? Just like it's doing with `list()` and `retrieve()`?

**Comment by jjlorenzo** [comment]
This is what I'm using, got some ideas from here and implement a simple solution that works for my case for now, I'll love if this could be formally implemented.

I'm using a nested router, under a `practice` resource, so I had `practice_pk` on `kwargs`

Sorry, for name clashing, since naming objects is difficult to me, I tend to put the same name under another module, I'll later refactor the example with all parts.

``` python
class ModelViewSet(viewsets.ModelViewSet):
  @property
  def _lookup_attrs(self):
    return {key.replace('pk', 'id'): value for key, value in six.iteritems(self.kwargs)}

  def get_queryset(self):
    return super(ModelViewSet, self).get_queryset().filter(**self._lookup_attrs)

  def perform_create(self, serializer):
    attrs = self._lookup_attrs

    # set `updated_by` to the current user if it was declared as `read_only`
    if 'updated_by' in serializer.fields and serializer.fields['updated_by'].read_only:
      attrs.update({'updated_by_id': self.request.user.pk})

    serializer.save(**attrs)
```

``` python
class ConsentFormTemplate(ModelViewSet):

  queryset = models.ConsentFormTemplate.objects.all()

  serializer_class = serializers.ConsentFormTemplate


class ConsentFormTemplate(serializers.ModelSerializer):

  class Meta:

    model = models.ConsentFormTemplate

    fields = [
      'id',
      'name',
      'practice',
      ....
      'updated_by',
    ]

    read_only_fields = [
      'id',
      'practice',
      ....
      'updated_by',
    ]

```

``` python
router_v2 = SimpleRouter()
# top level resources
router_v2.register(Practice.prefix, Practice.viewset)

router_v2_practice = NestedSimpleRouter(parent_router=router_v2, parent_prefix=Practice.prefix, lookup=Practice.lookup)
# every resource registered under `router_v2_practice` will be prefixed with practices/<practice_pk>/
router_v2_practice.register(ConsentFormTemplate.prefix, ConsentFormTemplate.viewset)

api_urls_v2 = [
  # url('', include(router_v2.urls)),
  url('', include(router_v2_practice.urls)),
]
```

``` python
Resource = namedtuple(
  typename='Resource',
  field_names='prefix viewset base_name lookup'
)
# http://stackoverflow.com/questions/11351032/named-tuple-and-optional-keyword-arguments/18348004#18348004
Resource.__new__.__defaults__ = (None, None)

ConsentFormTemplate = Resource(prefix=r'consent-form-templates', viewset=views.ConsentFormTemplate)
```

**Comment by claradaia** [comment]
I know this is an old question, but I did not like any of the proposed solutions and thought I'd share what I did instead, in case it is useful for someone else:

* Created a write-only field for the FK in the nested model serializer:
```
class NestedModelSerializer(serializers.ModelSerializer):

    parent_model_fk_field = serializers.PrimaryKeyRelatedField(write_only=True,
                                                                            queryset=ParentModel.objects.all())
```

* Copied the `create` and `update` methods from the respective mixin classes and changed them as such:
```
class NestedModelViewSet(viewsets.ModelViewSet):
    [...]

    def create(self, request, *args, **kwargs):
        -serializer = self.get_serializer(data=request.data)
        +data = request.data
        +data.update({'parent_model_fk_field': self.kwargs['parent_model_id']})
        +serializer = self.get_serializer(data=data)
        serializer.is_valid(raise_exception=True)
        [...]
```

That way the parent PK is validated inside the serializer, which makes more sense to me. _Of course_ the PK would not be invalid because the library took care of that, but I prefer to have the restriction in a 'declarative way' inside the serializer. Should I ever change the structure of my code to not use nested routes, the serializer will change very little.

**Comment by claradaia** [comment]
Indeed. Not sure whether this one falls in "practicality beats purity" or in "explicit is better than implicit" hehe.

**Comment by Mogost** [comment]
Actually, this issue is not resolved. Now `drf-nested-routers` has unexpected behavior and this behavior may cause security problems.
