### ISSUE TITLE
Update release on pypi?

### ISSUE THREAD

**Issue by bharling** [alanjds/drf-nested-routers#92]
Hi,

I've included the github master of drf-nested-routers in our project and it's really working well, seems to do exactly what we need. We'd really prefer to include a pypi release in our deps rather than building the library for each release, do you have a timescale for the next pypi release?

thanks!

**Comment by alanjds** [comment]
Yes. I was waiting some sunsets to let bugreports to happen. I expect to release on PyPI in the next 2 weeks.

**Comment by bharling** [comment]
Good news thankyou. From my ( fairly limited ) testing all seems well with it at least.

**Comment by ChristianKreuzberger** [comment]
No issues from my side with the software I already have in production :)

**Comment by anx-ckreuzberger** [comment]
Any news? It's still working for me with commit id 0438289612eec0bc450a290b5fd6ecf5ccec4673

**Comment by alanjds** [comment]
Yeah... Nothing is blocking it yet. I am delayed for lack of time. Hope to release it yesterday :(

**Comment by alanjds** [comment]
Just released [v0.90.0](https://pypi.python.org/pypi/drf-nested-routers/0.90.0).

**Comment by alanjds** [comment]
I am very happy with this release, supporting a HyperlinkRelated field with infinite nesting. Thanks all ones that contributed code, issues and ideas, specially @ChristianKreuzberger and @c17r for fixing lots of it.

Is not tagged 1.0 because have not very important "soft" stuff like proper docs (not a giant README), official Python 3 support and a deprecation policy. Next release will be for this soft stuff only (I hope) and very very soon (I pray).

Thanks again for all using and helping this project.

**Comment by anx-ckreuzberger** [comment]
I am also very happy that this my proposed changes made it into nested routers :)

Also good call about 0.9 instead of 1.0. Hopefully others can also contribute some parts of the docs. I'm busy writing some login/logout stuff for another project of mine atm, but once that is finished I might look into the docs and Python3 support.

**Comment by c17r** [comment]
I do all my development on Python 3 and have had no trouble with drf-nested-routers.

**Comment by anx-ckreuzberger** [comment]
Now that you mention it... I do too :P

Python3.4+ works perfect for me.

Maybe it's just about having the unittests run in Python3?
